version: '3.2'

services:

  harvester-api:
    #build: .
    image: &app registry.cn-beijing.aliyuncs.com/yk060520/substrate-api:latest
    ports:
      - '8000:8000'
    volumes:
      - '.:/usr/src/app'
    command: ./start.sh
    environment: &env
      - CELERY_BROKER=redis://103.224.250.19:6379/0
      - CELERY_BACKEND=redis://103.224.250.19:6379/1
#      - CELERY_BROKER=redis://192.168.1.141:6379/0
#      - CELERY_BACKEND=redis://192.168.1.141:6379/1
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=dev
      - SUBSTRATE_METADATA_VERSION=11
      - DB_USERNAME=polkascan
      - DB_PASSWORD=polkascan
#      - DB_HOST=192.168.1.141
      - DB_HOST=103.224.250.19
      - DB_NAME=polkascan
      - DB_PORT=3306
#      - DB_CONNECTION=mysql+mysqlconnector://root:root@192.168.1.141:3306/polkascan
      - DB_CONNECTION=mysql+mysqlconnector://polkascan:polkascan@103.224.250.19:3306/polkascan
      - TZ=Asia/Shanghai
#      - SET_CONTAINER_TIMEZONE=true
#      - CONTAINER_TIMEZONE=Asia/Shanghai
    #links:
    #  - mysql
    #  - redis
    #depends_on:
      #- redis
      #- mysql
      #- substrate-node

  harvester-worker:
    #build: .
    image: *app
    volumes:
      - '.:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
    #depends_on:
    #  - redis
    #  - mysql

  harvester-beat:
    # build: .
    image: *app
    volumes:
      - '.:/usr/src/app'
    command: celery -A app.tasks beat --loglevel=INFO --schedule= --pidfile=
    environment: *env
    #depends_on:
    #  - redis

  harvester-monitor:
    # build: .
    image: *app
    ports:
      - '5555:5555'
#    command:  flower -A app.tasks --port=5555 --broker=redis://192.168.1.141:6379/0
    command:  flower -A app.tasks --port=5555 --broker=redis://103.224.250.19:6379/0
    #depends_on:
    #  - redis

  redis:
    image: redis:3.2.11

  mysql:
    image: mysql:latest
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkascan

  substrate-node:
    image: polkasource/substrate-alexander:latest
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
    command: --dev --rpc-port 9933 --rpc-external --pruning=10000000